# Generated by Django 4.0 on 2022-10-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('INSURANCE', 'Car Insurance'), ('RENTAL', 'House Rental'), ('Food', (('GROCERY', 'Grocery'), ('ORDER', 'Food Order'))), ('LOAN', 'Car Loan')], max_length=250),
        ),
    ]
