# Generated by Django 4.0 on 2022-11-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='date',
            new_name='purchase_date',
        ),
    ]
