# Generated by Django 4.0 on 2022-11-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_rename_quantity_purchase_purchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_unit',
            field=models.CharField(blank=True, choices=[('IM', 'Imported'), ('LOC', 'Local')], max_length=250),
        ),
    ]
