# Generated by Django 4.0 on 2022-11-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product_unit',
            field=models.CharField(blank=True, choices=[('KILOGRAM', 'kg'), ('PIECES', 'pcs')], max_length=250),
        ),
    ]
