# Generated by Django 4.0 on 2022-11-13 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0016_alter_sales_delivery_receipt_alter_sales_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_date', models.DateField(default=django.utils.timezone.now)),
                ('inv_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.products')),
                ('product_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.productunit')),
            ],
            options={
                'verbose_name': 'Inventories',
            },
        ),
    ]
