# Generated by Django 4.0 on 2022-11-13 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_sales_owner'),
        ('inventory', '0006_remove_inventory_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.products'),
        ),
    ]
