# Generated by Django 4.0 on 2022-11-14 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sales', '0018_alter_sales_owner'),
        ('inventory', '0007_inventory_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTotalInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_inventory_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inv_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorytype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.products')),
                ('product_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.productunit')),
            ],
        ),
    ]
