# Generated by Django 4.0 on 2022-11-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_currenttotalinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currenttotalinventory',
            options={'verbose_name_plural': 'Current Total Inventories'},
        ),
    ]
