# Generated by Django 4.0 on 2022-11-14 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_currenttotalinventory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytype',
            options={'verbose_name_plural': 'Inventory Types'},
        ),
        migrations.AddField(
            model_name='currenttotalinventory',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
