# Generated by Django 4.0 on 2022-11-14 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventorytype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenttotalinventory',
            name='current_inventory_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='currenttotalinventory',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
