# Generated by Django 4.0 on 2022-11-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_inv_date_inventory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='current_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.currenttotalinventory'),
        ),
    ]
