# Generated by Django 4.0 on 2022-11-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_inventory_current_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.CharField(default='Supplier', max_length=250),
        ),
    ]
