# Generated by Django 4.0 on 2022-11-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_inventory_current_inventory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransactions',
            options={'verbose_name_plural': 'Inventory Transactions'},
        ),
        migrations.AlterField(
            model_name='inventorytransactions',
            name='customer_supplier',
            field=models.CharField(max_length=250, verbose_name='Customer/Supplier'),
        ),
    ]
