# Generated by Django 4.0 on 2022-11-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_inventorytransactions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransactions',
            options={'ordering': ['date'], 'verbose_name_plural': 'Inventory Transactions'},
        ),
    ]
