# Generated by Django 4.0 on 2022-11-27 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_inventorytransactions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttotalinventory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
