# Generated by Django 4.0 on 2022-10-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(blank=True, default='Canadian Dollar', max_length=150, null=True),
        ),
    ]
