# Generated by Django 4.0 on 2022-11-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_productname_alter_sales_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductName',
            new_name='Products',
        ),
    ]
