# Generated by Django 4.0 on 2022-11-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sales_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='products',
            new_name='product_name',
        ),
    ]
