# Generated by Django 4.0 on 2022-11-07 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_products_sales_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
