# Generated by Django 4.0 on 2022-11-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sales_sales_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='quantity',
            new_name='sold_quantity',
        ),
    ]
