# Generated by Django 4.0 on 2022-11-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sales', '0008_rename_quantity_sales_sold_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
