# Generated by Django 4.0 on 2022-11-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_sales_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
