# Generated by Django 4.0 on 2022-11-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['name'], 'verbose_name_plural': 'Products'},
        ),
    ]
