# Generated by Django 4.0 on 2022-11-12 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_productunit_sales_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='delivery_receipt',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='invoice',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
