# Generated by Django 4.0 on 2022-11-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_soldtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sold_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.soldtype'),
        ),
    ]
