# Generated by Django 4.0 on 2022-11-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_sales_sold_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-sales_date'], 'verbose_name_plural': 'Sales'},
        ),
    ]
