# Generated by Django 4.0 on 2022-11-15 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_sales_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
    ]
