# Generated by Django 4.0 on 2022-11-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_sales_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='date',
            new_name='my_date',
        ),
    ]
