# Generated by Django 4.0 on 2022-11-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_rename_date_sales_my_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='my_date',
        ),
    ]
