# Generated by Django 4.0 on 2022-11-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_remove_sales_my_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='sales_date',
            new_name='date',
        ),
    ]
