# Generated by Django 4.0 on 2022-11-16 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_remove_sales_current_inventory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name_plural': 'Sales'},
        ),
    ]
