# Generated by Django 4.0 on 2022-11-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_alter_sales_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='current_inventory',
        ),
    ]
