# Generated by Django 4.0 on 2023-09-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_remove_sales_current_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.productunit'),
        ),
        migrations.AddField(
            model_name='sales',
            name='margin',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='margin_percent',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='delivery_receipt',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='invoice',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sold_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
